# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-03 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name=b'email')),
                ('first_name', models.CharField(blank=True, max_length=15, verbose_name=b'First name')),
                ('last_name', models.CharField(blank=True, max_length=15, verbose_name=b'Last name')),
                ('avatar', models.ImageField(blank=True, upload_to=b'', verbose_name=b'avatar')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Name')),
                ('year', models.IntegerField(verbose_name=b'Year')),
                ('color', models.CharField(max_length=7, verbose_name=b'Color')),
                ('pantone_value', models.CharField(max_length=15, verbose_name=b'Pantone value')),
            ],
            options={
                'db_table': 'product',
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
